import ProtectedRoutes from "@/components/ProtectedRoutes";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { UserProvider } from "@/context/UserContext";
import { AuthModalProvider } from "@/context/AuthModalContext";
import AuthModal from "@/components/AuthModal/AuthModal";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <UserProvider>
          <AuthModalProvider>
            <ProtectedRoutes>
              <Navbar />
              {children}
              <AuthModal />
            </ProtectedRoutes>
          </AuthModalProvider>
        </UserProvider>
      </body>
    </html>
  );
}
