import ProtectedRoutes from "@/components/ProtectedRoutes";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import {
  MobileMenuContext,
  MobileMenuContextProvider,
} from "@/context/MobileMenuContext";
import MobileMenu from "@/components/MobileMenu/MobileMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <ProtectedRoutes>
        <body>
          <Navbar />
          {children}
          <MobileMenu />
        </body>
      </ProtectedRoutes>
    </html>
  );
}
