import ProtectedRoutes from "@/components/ProtectedRoutes";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { UserProvider } from "@/context/UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <UserProvider>
          <ProtectedRoutes>
            <Navbar />
            {children}
          </ProtectedRoutes>
        </UserProvider>
      </body>
    </html>
  );
}
